import { Order } from '@dreckly/types';

export const getOrders = async (): Promise<Order[]> => {
  return [
    {
      id: '1001',
      userId: 1,
      restaurantId: 1,
      restaurantName: 'The Cornish Pasty Co.',
      items: [
        {
          id: '1',
          name: 'Traditional Pasty',
          price: 4.5,
          quantity: 2,
          total: 9.0,
        },
        {
          id: '6',
          name: 'Cornish Yarg Cheese',
          price: 3.25,
          quantity: 1,
          total: 3.25,
        },
      ],
      subtotal: 12.25,
      deliveryFee: 2.99,
      total: 15.24,
      status: 'delivered',
      orderDate: '2025-01-15T18:30:00Z',
      estimatedDeliveryTime: '2025-01-15T19:15:00Z',
      actualDeliveryTime: '2025-01-15T19:12:00Z',
      deliveryAddress: {
        line1: '15 Lemon Street',
        line2: '',
        city: 'Truro',
        postcode: 'TR1 2LQ',
      },
      specialInstructions: 'Please ring doorbell on delivery',
    },
    {
      id: '1002',
      userId: 1,
      restaurantId: 2,
      restaurantName: "Fisherman's Catch",
      items: [
        {
          id: '8',
          name: 'Fish & Chips',
          price: 8.99,
          quantity: 1,
          total: 8.99,
        },
        {
          id: '11',
          name: 'Mushy Peas',
          price: 1.5,
          quantity: 1,
          total: 1.5,
        },
        {
          id: '12',
          name: 'Curry Sauce',
          price: 1.0,
          quantity: 1,
          total: 1.0,
        },
      ],
      subtotal: 11.49,
      deliveryFee: 3.49,
      total: 14.98,
      status: 'delivered',
      orderDate: '2025-01-10T19:00:00Z',
      estimatedDeliveryTime: '2025-01-10T19:45:00Z',
      actualDeliveryTime: '2025-01-10T19:42:00Z',
      deliveryAddress: {
        line1: '15 Lemon Street',
        line2: '',
        city: 'Truro',
        postcode: 'TR1 2LQ',
      },
    },
    {
      id: '1003',
      userId: 1,
      restaurantId: 3,
      restaurantName: 'Kernow Kitchen',
      items: [
        {
          id: '13',
          name: 'Cornish Crab Cakes',
          price: 6.5,
          quantity: 1,
          total: 6.5,
        },
        {
          id: '15',
          name: 'Lamb Shank',
          price: 16.99,
          quantity: 1,
          total: 16.99,
        },
      ],
      subtotal: 23.49,
      deliveryFee: 2.49,
      total: 25.98,
      status: 'delivered',
      orderDate: '2025-01-20T18:45:00Z',
      estimatedDeliveryTime: '2025-01-20T19:35:00Z',
      actualDeliveryTime: '2025-01-20T19:32:00Z',
      deliveryAddress: {
        line1: '15 Lemon Street',
        line2: '',
        city: 'Truro',
        postcode: 'TR1 2LQ',
      },
      specialInstructions: 'Please leave with concierge if not home',
    },
    {
      id: '1004',
      userId: 1,
      restaurantId: 4,
      restaurantName: 'Seaside Spice',
      items: [
        {
          id: '17',
          name: 'Chicken Tikka Masala',
          price: 12.99,
          quantity: 1,
          total: 12.99,
        },
        {
          id: '18',
          name: 'Pilau Rice',
          price: 3.5,
          quantity: 1,
          total: 3.5,
        },
        {
          id: '19',
          name: 'Naan Bread',
          price: 2.5,
          quantity: 2,
          total: 5.0,
        },
      ],
      subtotal: 21.49,
      deliveryFee: 2.99,
      total: 24.48,
      status: 'delivered',
      orderDate: '2025-01-20T19:15:00Z',
      estimatedDeliveryTime: '2025-01-20T20:05:00Z',
      actualDeliveryTime: '2025-01-20T20:02:00Z',
      deliveryAddress: {
        line1: '15 Lemon Street',
        line2: '',
        city: 'Truro',
        postcode: 'TR1 2LQ',
      },
    },
    {
      id: '1005',
      userId: 1,
      restaurantId: 5,
      restaurantName: 'The Cornish Creamery',
      items: [
        {
          id: '25',
          name: 'Cornish Ice Cream',
          price: 4.5,
          quantity: 2,
          total: 9.0,
        },
        {
          id: '26',
          name: 'Cream Tea',
          price: 6.99,
          quantity: 1,
          total: 6.99,
        },
      ],
      subtotal: 15.99,
      deliveryFee: 2.49,
      total: 18.48,
      status: 'delivered',
      orderDate: '2025-01-20T19:30:00Z',
      estimatedDeliveryTime: '2025-01-20T20:20:00Z',
      actualDeliveryTime: '2025-01-20T20:17:00Z',
      deliveryAddress: {
        line1: '15 Lemon Street',
        line2: '',
        city: 'Truro',
        postcode: 'TR1 2LQ',
      },
    },
  ];
};
